name: Commit
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
env:
  GO_VERSION: 1.22

jobs:
  style:
    name: Code style check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          cache: false
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/.cache/golangci-lint
            ~/go/pkg/mod
            ~/go/bin
          key: code-style-check-${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum', 'Makefile') }}
      - run: make check

  test:
    name: Build and Test ${{ matrix.envoy-image }}
    strategy:
      fail-fast: false
      matrix:
        envoyx-image:
        - v1.30-latest-envoyx-v0.1.0
        - v1.29-latest-envoyx-v0.1.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          cache: false
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/.cache/golangci-lint
            ~/go/pkg/mod
            ~/go/bin
          key: build-and-test-${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum', 'Makefile') }}
      - name: Build
        run: make build
      - name: Unit tests
        run: make test
      - name: Install Envoy
        run: |
          export ENVOY_BIN_DIR=$HOME/envoy/bin
          mkdir -p $ENVOY_BIN_DIR
          docker run -v $ENVOY_BIN_DIR:/work/go-sdk -w /work/go-sdk \
            --entrypoint /bin/cp ghcr.io/envoyproxyx/envoy:${{ matrix.envoy-image }} /usr/local/bin/envoy .
          echo $ENVOY_BIN_DIR >> $GITHUB_PATH
      - name: Integration E2E tests
        run: make e2e