name: Commit
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
env:
  GO_VERSION: 1.22

jobs:
  style:
    name: Code style check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          cache: false
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/.cache/golangci-lint
            ~/go/pkg/mod
            ~/go/bin
          key: code-style-check-${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum', 'Makefile') }}
      - run: make check

  test:
    name: Build and Test (envoy:${{ matrix.version.envoy_image_tag }})
    strategy:
      fail-fast: false
      matrix:
        version:
        - envoy_image_tag: v1.31-latest
        - envoy_image_tag: v1.30-latest
        - envoy_image_tag: v1.29-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          cache: false
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/.cache/golangci-lint
            ~/go/pkg/mod
            ~/go/bin
          key: build-and-test-${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum', 'Makefile') }}-${{ matrix.version.envoy_image_tag }}

      - name: Build
        run: make build

      - name: Unit tests
        run: make test

      - name: Install Envoy
        run: |
          export ENVOY_BIN_DIR=$HOME/envoy/bin
          mkdir -p $ENVOY_BIN_DIR
          docker run -v $ENVOY_BIN_DIR:/work/go-sdk -w /work/go-sdk \
            --entrypoint /bin/cp ghcr.io/mathetake/envoy:${{ matrix.version.envoy_image_tag }} /usr/local/bin/envoy .
          echo $ENVOY_BIN_DIR >> $GITHUB_PATH

      - name: Conformance tests
        run: make conformance
