name: Commit
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
env:
  GO_VERSION: 1.22

jobs:
  style:
    name: Code style check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          cache: false
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/.cache/golangci-lint
            ~/go/pkg/mod
            ~/go/bin
          key: code-style-check-${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum', 'Makefile') }}
      - run: make check

  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          cache: false
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/.cache/golangci-lint
            ~/go/pkg/mod
            ~/go/bin
          key: build-and-test-${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum', 'Makefile') }}
      - run: make build
      - run: make test